### ISSUE TITLE
incorrect call to set_element

### ISSUE THREAD

**Issue by dkoes** [dkoes/md-scripts#2]
https://github.com/dkoes/md-scripts/blob/b1f92422f20aa072b1caa03724c99b46e8a4125c/simplepdb.py#L75

set_element is a method, but it is being called as a standalone function here.  Calling as a method doesn't work unless you first set self.moldata

**Comment by dkoes** [comment]
This error was found by inadvertently calling prepare_amber on an empty file (END)

**Comment by Jsunseri** [comment]
fixed 29dea0ef5c2bf6de6cd22d745e9120bfcafb1191
