### ISSUE TITLE
prepareamber.py fails unless a second force-field is specified

### ISSUE THREAD

**Issue by francoep** [dkoes/md-scripts#5]
If the `-eff` option is not passed when running prepareamber.py  you get the following error

```
Warning: force field not found in /home/dkoes/build/amber18! This is likely to cause problems later.
Traceback (most recent call last):
 File "prepareamber.py", line 474, in <module>
  nff = find_ff(amberhome, args.extra_force_field)
 File "prepareamber.py", line 62, in find_ff
  return ff
UnboundLocalError: local variable 'ff' referenced before assignment
```

I believe this is due to the find_ff function breaking when being passed in an empty string. I'm not sure what else breaks.

**Comment by Jsunseri** [comment]
should be fixed with commit e68a9394a0d151babdb6e0b3fad953d92f5a5cb5
that was based on a simple test; let me know if it's still broken. thanks!
